---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: events-pod-view
  namespace: kubeless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-pod
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubeless

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-pod
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeless-nats-events
  namespace: kubeless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeless-nats-events
  template:
    metadata:
      labels:
        app: kubeless-nats-events
    spec:
      containers:
      - command:
        - ./main.py
        - --in-cluster
        - --output-events
        env:
        - name: NATS_ADDRESS
          value: nats-cluster.nats-io
        image: jaxxstorm/kubernetes-events:latest
        name: master
        resources:
          requests:
            cpu: 100m
            memory: 100Mi