falco:
  version: 0.26.2
  exporter_version: 0.4.1
  pod_security_policy: false
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  ebpf:
    enable: false
  audit_log:
    enable: false
    dynamic_backend_enable: false