longhorn:
  manager_image: docker.io/longhornio/longhorn-manager:v1.0.0
  engine_image: docker.io/longhornio/longhorn-engine:v1.0.0
  instance_manager_image: docker.io/longhornio/longhorn-instance-manager:v1_20200514
  ui_image: longhornio/longhorn-ui:v1.0.0
  ingress_host: longhorn
  default_storageclass:
    enabled: false
    name: longhorn