openfaas:
  client_version: 0.12.19
  client_source_hash: 4798f7d391508df970b32ea4a7f3ec0c09c820ffcc8317853402577eab5247ec
  oauth2_image: alexellis2/openfaas-oidc-plugin:0.2.6
  nats_connector_image: openfaas/nats-connector:0.2.2
  ingress_host: openfaas
  username: admin
  password: V3ry1ns3cur3
  nats_topics: "nats_test,"
  oauth:
    enabled: False
    provider: keycloak
    keycloak:
      realm: default
