kube_prometheus:
  version: master
  grafana_image: docker.io/grafana/grafana:7.3.0
  grafana_ingress_host: grafana
  altermanager_ingress_host: alertmanager
  prometheus_ingress_host: prometheus
  pushgateway_image: prom/pushgateway:v1.2.0
  